import { ContentContainer } from "@/components/content-container";
import { PageHeader } from "@/components/page-header";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased scroll-smooth bg-slate-100`}
      >
        <PageHeader />
        <ContentContainer>{children}</ContentContainer>
      </body>
    </html>
  );
}
