import { HeroCategoryMenu } from "@/components/hero-category-menu";
import { PageHeader } from "@/components/page-header";
import { getAllCategories } from "@/lib/content";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = getAllCategories();
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased scroll-smooth bg-slate-100`}
      >
        <PageHeader />
        <HeroCategoryMenu categories={categories} />
        {children}
      </body>
    </html>
  );
}
